### ISSUE TITLE
Checklist Test

### ISSUE THREAD

**Issue by ostranme** [ostranme/fun-with-readme#1]
- [x] Create initial readme
- [x] Explore how to use emojis in issues, comments, and pull request descriptions
- [x] Figure out header links vs anchors syntax

**Comment by ostranme** [comment]
This is an emoji test...

:tada: :bowtie:
